name: E2E Tests

permissions:
    contents: read

on:
    workflow_call:

jobs:
    php-e2e-tests-shopware-5-7:
        name: Shopware current
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/shopware5/docker-images-testing/install:shopware_5.7_8.0_8.2_none
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        env:
            PAYPAL_SANDBOX_CLIENT_ID: ${{ secrets.PAYPAL_SANDBOX_CLIENT_ID }}
            PAYPAL_SANDBOX_CLIENT_SECRET: ${{ secrets.PAYPAL_SANDBOX_CLIENT_SECRET }}
            PAYPAL_SANDBOX_MERCHANT_ID: ${{ secrets.PAYPAL_SANDBOX_MERCHANT_ID }}

            PAYPAL_CUSTOMER_EMAIL: ${{ secrets.PAYPAL_CUSTOMER_EMAIL }}
            PAYPAL_CUSTOMER_PASSWORD: ${{ secrets.PAYPAL_CUSTOMER_PASSWORD }}
            PAYPAL_CREDIT_CARD: ${{ secrets.PAYPAL_CREDIT_CARD }}

            PAYPAL_SEPA_IBAN: ${{ secrets.PAYPAL_SEPA_IBAN }}
            PAYPAL_SEPA_PHONE: ${{ secrets.PAYPAL_SEPA_PHONE }}
            PAYPAL_SEPA_BIRTHDAY: ${{ secrets.PAYPAL_SEPA_BIRTHDAY }}

        steps:
            -   run: /usr/bin/supervisord -c /etc/supervisord.conf &

            -   name: Checkout SwagPaymentPayPalUnified
                uses: actions/checkout@v3
                with:
                    path: plugin

            -   name: Move plugin
                run: mv "$(pwd)/plugin" /shopware/custom/plugins/SwagPaymentPayPalUnified

            -   name: Setup SwagPaymentPayPalUnified
                run: |
                    cd /shopware/custom/plugins/SwagPaymentPayPalUnified
                    make composer-install
                    make install-plugin
                    cd /shopware/custom/plugins/SwagPaymentPayPalUnified/Tests/E2E
                    npm install
                    npx playwright install --with-deps chromium

            -   name: Check
                run: |
                    ps aux
                    curl "http://$(hostname -i)"

            -   name: Execute E2E tests
                run: |
                    cd /shopware/custom/plugins/SwagPaymentPayPalUnified
                    make run-e2e-tests

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                if: ${{ failure() }}
                with:
                    name: E2E test results
                    path: /shopware/custom/plugins/SwagPaymentPayPalUnified/Tests/E2E/results
