name: PHPUnit Tests

on:
    push:
    workflow_call:

jobs:
    php-unit-tests-shopware-5-7:
        name: Shopware 5.7 PHP version 7.4 - 8.2

        strategy:
            matrix:
                php-version: ["7.4", "8.0", "8.1", "8.2"]

        runs-on: ubuntu-latest
        container:
            image: ghcr.io/shopware5/docker-images-testing/install:shopware_5.7_8.0_${{ matrix.php-version }}_none
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        steps:
            - run: /usr/bin/supervisord -c /etc/supervisord.conf &

            - name: Checkout SwagPaymentPayPalUnified
              uses: actions/checkout@v3
              with:
                path: "code"

            - run: mv "$(pwd)/code" /shopware/custom/plugins/SwagPaymentPayPalUnified

            - run: curl http://localhost:80

            - name: Setup SwagPaymentPayPalUnified
              run: |
                  cd /shopware/custom/plugins/SwagPaymentPayPalUnified
                  pwd
                  make composer-install
                  make install-plugin

            - run: |
                echo "<?php
                return [
                    'db' => [
                        'username' => getenv('DB_USER'),
                        'password' => getenv('DB_PASSWORD'),
                        'dbname' => getenv('DB_NAME'),
                        'host' => getenv('DB_HOST'),
                        'port' => getenv('DB_PORT'),
                    ],

                    'csrfProtection' => [
                        'frontend' => false,
                        'backend' => false,
                    ],

                    'logger' => [
                        'level' => \Shopware\Components\Logger::DEBUG,
                    ],

                    'front' => [
                        'noErrorHandler' => true,
                        'throwExceptions' => true,
                        'disableOutputBuffering' => true,
                        'showException' => true,
                    ],

                    'phpsettings' => [
                        'display_errors' => 1,
                    ],

                    'errorHandler' => [
                        'throwOnRecoverableError' => true,
                        'ignoredExceptionClasses' => [],
                    ],

                    'template' => [
                        'forceCompile' => true,
                    ],

                    'cache' => [
                        'backend' => 'Black-Hole',
                    ],
                ];" > /shopware/config.php

            - name: Execute PHP unit tests
              run: |
                  cd /shopware/custom/plugins/SwagPaymentPayPalUnified
                  make run-tests

            - name: Archive logs
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: Logs
                path: /shopware/var/log