name: PHPUnit Tests

on:
    workflow_call:

jobs:
    php-unit-tests-shopware-5-7:
        name: Shopware 5.7 PHP version 7.4 - 8.2

        strategy:
            matrix:
                php-version: [ '7.4', '8.0', '8.1', '8.2' ]

        runs-on: ubuntu-latest
        container:
            image: ghcr.io/shopware5/docker-images-testing/install:shopware_5.7_8.0_${{ matrix.php-version }}_none
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        steps:
            -   run: |
                    mv /shopware ${{ github.workspace }}/shopware

            -   name: Checkout SwagPaymentPayPalUnified
                uses: actions/checkout@v3
                with:
                    path: ${{ github.workspace }}/shopware/custom/plugins/SwagPaymentPayPalUnified

            -   name: Setup SwagPaymentPayPalUnified
                run: |
                    cd ${{ github.workspace }}/shopware/custom/plugins/SwagPaymentPayPalUnified
                    ls -l
                    make composer-install
                    ls -l
                    make install-plugin

            -   name: Execute PHP unit tests
                run: |
                    cd ${{ github.workspace }}/shopware/custom/plugins/SwagPaymentPayPalUnified
                    make run-tests
