name: Run

on:
    workflow_dispatch:
    push:
    schedule:
        -   cron: '30 02 * * *'

jobs:
    php-e2e-tests-shopware-5-7:
        name: E2E
        uses: ./.github/workflows/e2e-tests.yml
        secrets: inherit
